import { DocumentSnapshot, QueryDocumentSnapshot, collection, doc, onSnapshot, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { db } from "../../firebase-config";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import Post from "../../components/Post";
import { AnimatePresence, motion} from "framer-motion";
import Comment from "../../components/Comment";
import { CommentType } from "../../type/comment";




export default function PostDetail() {
  const navigate = useNavigate()
  const { id } = useParams();

  const [post, setPost] = useState<DocumentSnapshot>();
  const [comments, setComments] = useState<QueryDocumentSnapshot[]>([]);

  // get the post data

  useEffect(
    () => onSnapshot(doc(db, "posts", id as string), (snapshot) => setPost(snapshot)),
    [db, id]
  );

  // get comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id as string, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [db, id]);



  return (
    <div>
      {/* <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

        {/* Sidebar */}

        {/* Feed */}

        <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
          <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className="hoverEffect" onClick={() => navigate("/")}>
              <ArrowLeftIcon className="h-5 " />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>

          <Post id={id as string} post={post as DocumentSnapshot} />
          {comments.length > 0 && (
            <div className="">
              <AnimatePresence>
                {comments.map((comment) => (
                  <motion.div
                    key={comment.id}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 1 }}
                  >
                    <Comment
                      key={comment.id}
                      commentId={comment.id}
                      originalPostId={id as string}
                      comment={comment.data() as CommentType}
                    />
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          )}
        </div>

        {/* Widgets */}

        {/* Modal */}
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

{
  /* <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
<div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
  <div className="hoverEffect" onClick={() => router.push("/")}>
    <ArrowLeftIcon className="h-5 " />
  </div>
  <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
    Tweet
  </h2>
</div>

<Post id={id} post={post} />
{comments.length > 0 && (
  <div className="">
    <AnimatePresence>
      {comments.map((comment) => (
        <motion.div
          key={comment.id}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 1 }}
        >
          <Comment
            key={comment.id}
            commentId={comment.id}
            originalPostId={id}
            comment={comment.data()}
          />
        </motion.div>
      ))}
    </AnimatePresence>
  </div>
)}
</div> */
}
